### ISSUE TITLE
Quick start Tutorial is not displaying correctly

### ISSUE THREAD

**Issue by patricerosay** [osgi/osgi.enroute.bundles#7]
Hi,
I've followed the step-by-step EnRoute Tutorial but I'm stucked in the third step "Create Application" http://enroute.osgi.org/qs/300-application.html:
My Chrome browser shows raw HTML without angular formating.and its console logs the following errors:

http://localhost:8080/osgi.enroute.webresource/com.acme.prime.upper.application/1.0.0.201506051359/*.js Failed to load resource: the server responded with a status of 500 (Server Error)
http://localhost:8080/osgi.enroute.webresource/com.acme.prime.upper.application/1.0.0.201506051359/*.css Failed to load resource: the server responded with a status of 500 (Server Error)

while there's no error in the Eclipse console 
![image](https://cloud.githubusercontent.com/assets/3807032/8007797/7cabf0ba-0b9e-11e5-91e5-c2da73cf06a3.png)

I'm running on windows8 with the latest BNDTools version (3.0.0.DEV-20150603)

Do you have any idea of what could be wrong?
Please advise.

**Comment by pkriens** [comment]
Did you look in the log? If you run it in debug mode as described in the tutorial then you should get the web console. In the web console there is a log pane, otherwise you can type ‘log debug’ in the console.

Now, the message indicates that there is an error on ‘com.acme.prime.upper.application/1.0.0.201506051359/.js’, this misses an asterisk (‘*’) just before the ‘.js’. This might be a problem in the reporting or it might indicate that something is wrong in your index.html file. To check this, open the source of the index.html file when you have it in the browser and verify that the ‘*’ is really there.

If this is not the problem, could you zip your project (without the generated & bin directories) and share it with me?

Kind regards,

	Peter Kriens

**Comment by patricerosay** [comment]
Thank you for your answer Peter.

I've sent you a zip file of the project com.acme.prime (cnf and com.acme.prime.upper.application) by email.

Asterisks are correctly set. There's a typo in the defect description, but they're displayed on the screenshot.

In the Eclipse console, i can read:

2015-06-08 12:37:10.097:INFO:oejs.Server:jetty-8.1.14.v20131031
2015-06-08 12:37:10.133:INFO:oejs.AbstractConnector:Started SelectChannelConnector@0.0.0.0:8080
[INFO] Started Jetty 8.1.14.v20131031 at port(s) HTTP:8080 on context path /
[DEBUG] Ignoring Servlet Service {javax.servlet.Servlet}={felix.webconsole.label=xray, service.id=28, service.bundleid=1, service.scope=singleton}, alias is missing or empty
[DEBUG] Ignoring Servlet Service {javax.servlet.Servlet}={felix.webconsole.title=HTTP Service, service.vendor=Apache Software Foundation, service.description=HTTP Service Web Console Plugin, felix.webconsole.configprinter.modes=always, felix.webconsole.label=httpservice, service.id=34, service.bundleid=7, service.scope=singleton}, alias is missing or empty
[INFO] Detected extended HttpService. Filters enabled.
[DEBUG] Ignoring Servlet Service {javax.servlet.Servlet}={felix.webconsole.title=Http Whiteboard, service.description=Felix Http Whiteboard WebConsole Plugin and Configuration Printer, felix.webconsole.configprinter.modes=[txt,zip], felix.webconsole.label=httpwhiteboard, service.id=37, service.bundleid=7, service.scope=singleton}, alias is missing or empty
[INFO] Http service whiteboard started
Web server

In the X-Ray console:
8/6/2015 12:37:38	ERROR	Internal webserver error		java.io.FileNotFoundException: E:\dev\ws-rcp\com.acme.prime\workspace\com.acme.prime.upper.application\generated\fw\org.eclipse.osgi\4\data\osgi.enroute.webresource\1.0.0.201506081011\*.js-tmp (La syntaxe du nom de fichier, de répertoire ou de volume est incorrecte)

Note that the folder exists but is empty.

I'm waiting for your feedbacks.
Patrice

**Comment by patricerosay** [comment]
Thank you for your answer Peter.
This is copy of the reply i've let on Quick start Tutorial is not displaying correctly · Issue #7 · osgi/osgi.enroute.bundles
|   |
|   |  |   |   |   |   |   |
| Quick start Tutorial is not displaying correctly · Issue...Hi, I've followed the step-by-step EnRoute Tutorial but I'm stucked in the third step "Create Application" http://enroute.osgi.org/qs/300-application.html: My Chrom... |
|  |
| View on github.com | Preview by Yahoo |
|  |
|   |


Asterisks are correctly set. There's a typo in the defect description, but they're displayed on the screenshot.
In the Eclipse console, i can read:
2015-06-08 12:37:10.097:INFO:oejs.Server:jetty-8.1.14.v201310312015-06-08 12:37:10.133:INFO:oejs.AbstractConnector:Started SelectChannelConnector@0.0.0.0:8080[INFO] Started Jetty 8.1.14.v20131031 at port(s) HTTP:8080 on context path /[DEBUG] Ignoring Servlet Service {javax.servlet.Servlet}={felix.webconsole.label=xray, service.id=28, service.bundleid=1, service.scope=singleton}, alias is missing or empty[DEBUG] Ignoring Servlet Service {javax.servlet.Servlet}={felix.webconsole.title=HTTP Service, service.vendor=Apache Software Foundation, service.description=HTTP Service Web Console Plugin, felix.webconsole.configprinter.modes=always, felix.webconsole.label=httpservice, service.id=34, service.bundleid=7, service.scope=singleton}, alias is missing or empty[INFO] Detected extended HttpService. Filters enabled.[DEBUG] Ignoring Servlet Service {javax.servlet.Servlet}={felix.webconsole.title=Http Whiteboard, service.description=Felix Http Whiteboard WebConsole Plugin and Configuration Printer, felix.webconsole.configprinter.modes=[txt,zip], felix.webconsole.label=httpwhiteboard, service.id=37, service.bundleid=7, service.scope=singleton}, alias is missing or empty[INFO] Http service whiteboard startedWeb server
In the X-Ray console:8/6/2015 12:37:38 ERROR Internal webserver error java.io.FileNotFoundException: E:\dev\ws-rcp\com.acme.prime\workspace\com.acme.prime.upper.application\generated\fw\org.eclipse.osgi\4\data\osgi.enroute.webresource\1.0.0.201506081011\*.js-tmp (La syntaxe du nom de fichier, de répertoire ou de volume est incorrecte)
Note that the folder exists but is empty.
I'm waiting for your feedbacks.Patrice
 



     On Monday, June 8, 2015 9:20 AM, Peter Kriens <notifications@github.com> wrote:
   

 Did you look in the log? If you run it in debug mode as described in the tutorial then you should get the web console. In the web console there is a log pane, otherwise you can type ‘log debug’ in the console.

Now, the message indicates that there is an error on ‘com.acme.prime.upper.application/1.0.0.201506051359/.js’, this misses an asterisk (‘*’) just before the ‘.js’. This might be a problem in the reporting or it might indicate that something is wrong in your index.html file. To check this, open the source of the index.html file when you have it in the browser and verify that the ‘*’ is really there.

If this is not the problem, could you zip your project (without the generated & bin directories) and share it with me?

Kind regards,

 Peter Kriens

**Comment by pkriens** [comment]
The problem seems to be that on Windows a file name cannot contain ‘*’ :-( The buggy code tries to create a file with the ‘*’ (which works fine on *nix & Mac) fails on windows.

I’ve created a fixed version on JPM. You should be able to update it. Go to the Distro repo in the repositories view, select the osgi.enroute.web.simple.provider, and then call up a menu: select Update.

Kind regards,

	Peter Kriens

**Comment by patricerosay** [comment]
Peter,

I've just did what you told me to, but there a new issues appearing in the Resolution Resuls.Panel

Please advise,
Patrice

java.lang.RuntimeException: java.lang.RuntimeException: java.io.IOException: Could not open URL, [404] Not Found for 'http://www.knopflerfish.org/snapshots/5.0.1.snapshot_trunk_4309/maven2/org/knopflerfish/bundle/useradmin/4.1.0/useradmin-4.1.0.jar'
org.osgi.service.resolver.ResolutionException: java.lang.RuntimeException: java.lang.RuntimeException: java.io.IOException: Could not open URL, [404] Not Found for 'http://www.knopflerfish.org/snapshots/5.0.1.snapshot_trunk_4309/maven2/org/knopflerfish/bundle/useradmin/4.1.0/useradmin-4.1.0.jar'
	at biz.aQute.resolve.ResolveProcess.resolveRequired(ResolveProcess.java:50)
	at org.bndtools.core.resolve.ResolveOperation.run(ResolveOperation.java:87)
	at org.bndtools.core.resolve.ResolveJob.run(ResolveJob.java:57)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.io.IOException: Could not open URL, [404] Not Found for 'http://www.knopflerfish.org/snapshots/5.0.1.snapshot_trunk_4309/maven2/org/knopflerfish/bundle/useradmin/4.1.0/useradmin-4.1.0.jar'
	at biz.aQute.resolve.internal.BndrunResolveContext.init(BndrunResolveContext.java:127)
	at biz.aQute.resolve.GenericResolveContext.getMandatoryResources(GenericResolveContext.java:626)
	at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:123)
	at biz.aQute.resolve.BndResolver.resolve(BndResolver.java:24)
	at biz.aQute.resolve.ResolveProcess.resolveRequired(ResolveProcess.java:61)
	at biz.aQute.resolve.ResolveProcess.resolveRequired(ResolveProcess.java:46)
	... 3 more
Caused by: java.lang.RuntimeException: java.io.IOException: Could not open URL, [404] Not Found for 'http://www.knopflerfish.org/snapshots/5.0.1.snapshot_trunk_4309/maven2/org/knopflerfish/bundle/useradmin/4.1.0/useradmin-4.1.0.jar'
	at aQute.bnd.deployer.repository.wrapper.InfoRepositoryWrapper.init(InfoRepositoryWrapper.java:138)
	at aQute.bnd.deployer.repository.wrapper.InfoRepositoryWrapper.findProviders(InfoRepositoryWrapper.java:154)
	at aQute.bnd.deployer.repository.wrapper.Plugin.findProviders(Plugin.java:132)
	at biz.aQute.resolve.GenericResolveContext.findProviders(GenericResolveContext.java:255)
	at biz.aQute.resolve.internal.BndrunResolveContext.findFramework(BndrunResolveContext.java:323)
	at biz.aQute.resolve.internal.BndrunResolveContext.init(BndrunResolveContext.java:121)
	... 8 more
Caused by: java.io.IOException: Could not open URL, [404] Not Found for 'http://www.knopflerfish.org/snapshots/5.0.1.snapshot_trunk_4309/maven2/org/knopflerfish/bundle/useradmin/4.1.0/useradmin-4.1.0.jar'
	at aQute.bnd.jpm.StoredRevisionCache.getConnection(StoredRevisionCache.java:201)
	at aQute.bnd.jpm.StoredRevisionCache.doDownload(StoredRevisionCache.java:144)
	at aQute.bnd.jpm.StoredRevisionCache.download(StoredRevisionCache.java:104)
	at aQute.bnd.jpm.Repository.scheduleDownload(Repository.java:260)
	at aQute.bnd.jpm.Repository.getLocal(Repository.java:226)
	at aQute.bnd.jpm.Repository.get(Repository.java:209)
	at aQute.bnd.jpm.Repository.createResourceDescriptor(Repository.java:1972)
	at aQute.bnd.jpm.Repository.getDescriptor(Repository.java:2242)
	at aQute.bnd.deployer.repository.wrapper.InfoRepositoryWrapper.collectKeys(InfoRepositoryWrapper.java:196)
	at aQute.bnd.deployer.repository.wrapper.InfoRepositoryWrapper.init(InfoRepositoryWrapper.java:66)
	... 13 more

**Comment by pkriens** [comment]
It looks like Knopflerfish cleared their repository. Then again, this was fixed already some time ago I think? Possible you have an old distro? In the latest workspace the URL was already moved to JPM?

Anyway, you can either update org.knopflerfish.bundle.useradmin or replace your distro.json in cnf with the version in https://github.com/osgi/workspace/tree/master/cnf

Kind regards,

	Peter Kriens

**Comment by patricerosay** [comment]
I've started over the tutorial and it works fine now on Wndows8.
Rgds,
Patrice

**Comment by pkriens** [comment]
Thanks for the feedback, appreciated.

Kind regards,

	Peter Kriens
