### ISSUE TITLE
DTOsProvider.Enc put() Method with Appendable or OutputStream as parameter does not work as expected

### ISSUE THREAD

**Issue by mcurcija** [osgi/osgi.enroute.bundles#71]
Expected behavior:
put(Appendable) or put(OutputStream) should result with JSON content in targeted Appendable or OutputStream instance.

Reproducible against current "master" using following test: 
```
package osgi.enroute.dtos.bndlib.provider;
....
public class TestEncImpl extends TestCase {

	private static final String EXPECTED_ENCODED_CONTENT = "{\"id\":999,\"symbolicName\":\"com.example.test\"}";
	private static final BundleDTO bundleDTO = new BundleDTO();
	static {
		bundleDTO.id = 999;
		bundleDTO.symbolicName = "com.example.test";
	}

	private DTOs.Enc cut;

	public void setUp() throws Exception {
		cut = new DTOsProvider().encoder(bundleDTO);
	}

	public void testAppendable() throws Exception {
		try (Writer writer = new StringWriter()) {
			cut.put(writer);
			assertEquals(EXPECTED_ENCODED_CONTENT, writer.toString());
		}
	}

	public void testOutputStream() throws Exception {
		try (OutputStream os = new ByteArrayOutputStream()) {
			cut.put(os);
			assertEquals(EXPECTED_ENCODED_CONTENT, os.toString());
		}
		try (OutputStream os = new ByteArrayOutputStream()) {
			cut.put(os, "UTF-8");
			assertEquals(EXPECTED_ENCODED_CONTENT, os.toString());
		}
	}
}

```
Is [Replace enRoute DTO with new Felix implementation](https://github.com/osgi/osgi.enroute.bundles/issues/69) related?

**Comment by pkriens** [comment]
What is the test output?

**Comment by mcurcija** [comment]
Output for testAppendable:
```
junit.framework.ComparisonFailure: expected:<[{"id":999,"symbolicName":"com.example.test"}]> but was:<[]>
	at junit.framework.Assert.assertEquals(Assert.java:100)
	at junit.framework.Assert.assertEquals(Assert.java:107)
	at junit.framework.TestCase.assertEquals(TestCase.java:269)
	at osgi.enroute.dtos.bndlib.provider.TestEncImpl.testAppendable(TestEncImpl.java:31)
```

Implementation in `osgi.enroute.dtos.bndlib.provider.DTOsProvider.EncImpl.put(Appendable)`
tries to _put_ given Appendable instance instead of source. 
 
```
		@Override
		public void put(Appendable out) throws Exception {
			enc.put(out);
		}
```

The difference between both put methods with OutputStream as argument is clear: 

```
		@Override
		public void put(OutputStream out) throws Exception {
			codec.enc().charset("UTF-8").to(out).put(source);
		}

		@Override
		public void put(OutputStream out, String charset) throws Exception {
			enc.charset(charset).put(out);
		}

```

I can prepare pull request based on [contributing](https://github.com/osgi/osgi.enroute.bundles/blob/master/CONTRIBUTING.md) document along with basic DTOsProvider.Enc/Inc test.

**Comment by bjhargrave** [comment]
> I can prepare pull request based on contributing document along with basic DTOsProvider.Enc/Inc test.

Please do!
