### ISSUE TITLE
ConcurrentModificationException in osgi.enroute.rest.simple.provider

### ISSUE THREAD

**Issue by eliasvasylenko** [osgi/osgi.enroute.bundles#83]
When polling a rest service fairly frequently it sometimes fails with the following exception:

	java.util.ConcurrentModificationException
		at java.util.ArrayList.sort(ArrayList.java:1456)
		at java.util.Collections.sort(Collections.java:175)
		at osgi.enroute.rest.simple.provider.RestMapper.execute(RestMapper.java:262)
		at osgi.enroute.rest.simple.provider.RestServlet.service(RestServlet.java:66)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
		at org.apache.felix.http.base.internal.handler.ServletHandler.handle(ServletHandler.java:85)
		at org.apache.felix.http.base.internal.dispatch.InvocationChain.doFilter(InvocationChain.java:79)
		at org.apache.felix.http.base.internal.dispatch.Dispatcher.dispatch(Dispatcher.java:124)
		at org.apache.felix.http.base.internal.DispatcherServlet.service(DispatcherServlet.java:61)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
		at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:845)
		at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583)
		at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224)
		at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1160)
		at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
		at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
		at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1092)
		at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
		at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
		at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
		at org.eclipse.jetty.server.Server.handle(Server.java:518)
		at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
		at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:244)
		at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
		at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
		at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
		at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:246)
		at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:156)
		at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
		at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
		at java.lang.Thread.run(Thread.java:745)

**Comment by eliasvasylenko** [comment]
Looks simple enough, I'll submit a fix shortly.

**Comment by eliasvasylenko** [comment]
Done: #84.
